name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout latest code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (faster and caching support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image with cache support and tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nextjs-app:cache
          cache-to: type=inline

      # 5. Deploy to EC2 via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

            docker stop nextjs-app || true
            docker rm nextjs-app || true

            docker run -d --restart always -p 80:3000 --name nextjs-app ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

            docker image prune -f
